// Shared logic for generating the Homebrew formula for Mjolnir from a GitHub
// release. Pure helpers live here so packaging/homebrew/test can exercise
// them without touching the network or a real release.

// Prefix of the GitHub release archive names produced by release.yml. This is
// the crate name and is independent of the formula name.
export const RELEASE_BUNDLE_PREFIX = 'brokk-mjolnir';

export const RELEASE_DOWNLOAD_BASE =
  'https://github.com/BrokkAi/mjolnir/releases/download';

// The release targets the formula consumes. macOS ships one universal
// archive that serves both Apple Silicon and Intel; Homebrew-on-Linux covers
// the two glibc targets. Android and Windows releases exist but Homebrew
// does not serve them.
export const HOMEBREW_TARGETS = [
  'universal-apple-darwin',
  'x86_64-unknown-linux-gnu',
  'aarch64-unknown-linux-gnu',
];

export function versionFromTag(tag) {
  const m = /^v(\d+\.\d+\.\d+)$/.exec(tag);
  if (!m) {
    throw new Error(`release tag ${JSON.stringify(tag)} is not of the form vX.Y.Z`);
  }
  return m[1];
}

export function cargoTomlVersion(cargoTomlText) {
  // The [package] table opens the file; the workspace tables come later, so
  // the first `version = "..."` at line start is the crate version.
  const m = /^version\s*=\s*"([^"]+)"/m.exec(cargoTomlText);
  if (!m) throw new Error('could not find version in Cargo.toml');
  return m[1];
}

export function releaseAssetName(tag, target) {
  return `${RELEASE_BUNDLE_PREFIX}-${tag}-${target}.tar.gz`;
}

export function releaseAssetUrl(tag, target) {
  return `${RELEASE_DOWNLOAD_BASE}/${tag}/${releaseAssetName(tag, target)}`;
}

// Sidecar format written by release.yml: `<hex>  <filename>` (shasum -a 256
// output). Returns { sha256, filename }; rejects anything else so a corrupt
// or truncated sidecar fails the build instead of producing a bad formula.
export function parseSha256Sidecar(sidecarText) {
  const m = /^([0-9a-fA-F]{64})\s+\*?(\S+)$/.exec(sidecarText.trim());
  if (!m) throw new Error('unparseable sha256 sidecar');
  return { sha256: m[1].toLowerCase(), filename: m[2] };
}

function assertSha256(sha, target) {
  if (typeof sha !== 'string' || !/^[0-9a-f]{64}$/.test(sha)) {
    throw new Error(
      `missing or malformed sha256 for ${target}: ${JSON.stringify(sha)}`,
    );
  }
}

// Render the complete Formula/mjolnir.rb text. `shas` maps each entry of
// HOMEBREW_TARGETS to the lowercase hex sha256 of its release archive.
export function renderFormula({ version, tag, shas }) {
  if (versionFromTag(tag) !== version) {
    throw new Error(`tag ${tag} does not match version ${version}`);
  }
  for (const target of HOMEBREW_TARGETS) {
    assertSha256(shas[target], target);
  }

  const url = (target) => releaseAssetUrl(tag, target);
  return `# typed: false
# frozen_string_literal: true

# Generated by packaging/homebrew/generate.mjs in BrokkAi/mjolnir.
# Do not edit by hand; regenerate from a release instead.
class Mjolnir < Formula
  desc "Forge-grade terminal client for any Agent Client Protocol (ACP) server"
  homepage "https://mjolnir.brokk.ai"
  license "GPL-3.0-only"
  version "${version}"

  on_macos do
    # One universal archive serves both Apple Silicon and Intel.
    url "${url('universal-apple-darwin')}"
    sha256 "${shas['universal-apple-darwin']}"
  end

  on_linux do
    on_intel do
      url "${url('x86_64-unknown-linux-gnu')}"
      sha256 "${shas['x86_64-unknown-linux-gnu']}"
    end
    on_arm do
      url "${url('aarch64-unknown-linux-gnu')}"
      sha256 "${shas['aarch64-unknown-linux-gnu']}"
    end
  end

  def install
    # The release archive has a single top-level directory; Homebrew strips
    # it during unpacking, so the binaries are staged at the top level.
    bin.install "mj", "anvil", "mj-voice-worker"
  end

  def caveats
    <<~EOS
      This formula installs mj together with its sibling binaries anvil and
      mj-voice-worker, so voice dictation works out of the box.

      Bifrost is not included. See https://mjolnir.brokk.ai/install/ if you
      need it.

      Upgrades come from Homebrew (brew upgrade mjolnir); do not use
      Mjolnir's in-place self-updater under a brew installation.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mj --version")
  end
end
`;
}
