//! Hel's reusable controller, worker, and session-management core.

mod claude_usage;
pub mod clock;
mod codex_usage;
mod grok_usage;
pub mod speech;
pub mod termination;
pub mod usage_format;

pub mod hel_acp;
pub mod hel_archive;
pub mod hel_chat;
pub mod hel_checkpoint;
pub mod hel_clipboard;
pub mod hel_compaction;
pub mod hel_config;
pub mod hel_controller;
pub mod hel_credentials;
pub mod hel_database;
pub mod hel_desktop;
pub mod hel_diff;
pub mod hel_doctor;
pub mod hel_elicitation;
pub mod hel_git_proxy;
pub mod hel_import;
pub mod hel_local_git;
pub mod hel_project_memory;
pub mod hel_projection;
pub mod hel_quota;
pub mod hel_readline;
pub mod hel_recovery;
pub mod hel_resources;
pub mod hel_review;
pub mod hel_second_opinion;
pub mod hel_selection;
pub mod hel_server;
pub mod hel_session_manager;
pub mod hel_setup;
pub mod hel_skills;
pub mod hel_state;
pub mod hel_subprocess;
pub mod hel_tailscale;
pub mod hel_targets;
pub mod hel_terminal;
pub mod hel_test_hooks;
pub mod hel_text_input;
pub mod hel_transcript;
pub mod hel_user_shell;
pub mod hel_worker;
pub mod hel_worker_client;
pub mod hel_worker_protocol;
pub mod hel_worker_runtime;
pub mod hel_workspace;
