//! Mjolnir shared contracts, formats, pure projections and reusable utilities.

pub mod clock;

pub mod acp;
pub mod activity;
pub mod archive;
pub mod assessment;
pub mod attachment;
pub mod bounded_frame;
pub mod codex_catalog;
pub mod codex_provider;
pub mod config;
pub mod credentials;
pub mod diagnostic;
pub mod diff;
pub mod effort_verdict;
pub mod elicitation;
pub mod event_outcome;
pub mod github_item;
pub mod go;
pub mod goal;
#[cfg(feature = "golden")]
pub mod golden;
pub mod harness_runtime;
pub mod help_search;
pub mod hex;
pub mod history;
pub mod jev;
pub mod local_git;
pub mod local_sockets;
pub mod login_environment;
pub mod mailbox;
pub mod move_workspace;
pub mod native_agent;
pub mod path_completion;
pub mod path_input;
pub mod profile_capabilities;
pub mod program_path;
pub mod project_catalog;
pub mod project_memory;
pub mod project_picker;
pub mod refusal;
pub mod relay;
pub mod remote_git;
pub mod repository;
pub mod review;
pub mod runtime;
pub mod second_opinion;
pub mod skills;
pub mod snapshot_map;
pub mod state;
pub mod storage;
pub mod subagent;
pub mod subprocess;
pub mod target_path;
pub mod targets;
pub mod test_hooks;
pub mod text;
pub mod transcript;
pub mod usage;
pub mod worker_build;
pub mod worker_launch;
pub mod worker_protocol;
pub mod workspace;

pub mod continuation;

pub mod cpu_usage;
